define([], function() {
  return {
    "userLang": "EN",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Community Name",
    "ListTemplateFieldLabel": "List name",
    "TitleCreate": "Title create",
    "createSpace": "Create a community",
    "paragrapheHome": "Collaborate with your colleagues across departments using Microsoft Teams and SharePoint, where ideas and documents flow easily between the two.",
    "startButton": "Let's go!",
    "powered": "Powered by",
    "gcx": "gcxchange",
    "menuFinal": "Let's do this",
    "menuOwners": "Invite owners",
    "menuTell": "Tell us more",
    "menuSpace": "Name your community",
    "menuTemplate": "Choose your template",
    "titleTemplate": "Choose your Sharepoint template",
    "paragrapheTemplate": "SharePoint is your community’s storefront that promotes your community to gcxchange visitors. Select a template that best fits your community's purpose. You will be able to modify it once it has been created.",
    "titleSpace": "Give your community a bilingual name",
    "paragrapheSpace": "Why a bilingual name? A bilingual name complies with the Official Languages Act and makes it easier for others to find your SharePoint community in the gcxchange Catalogue.",
    "validationTxtSpace": "Each name must contain letters and numbers only. Each one must be a minimum of 5 characters and a maximum of 125 characters long.",
    "english": "English",
    "french": "French",
    "validationSpaceInput": "Must contain letters and numbers only",
    "greatChoice": "Great choice!",
    "siteTaken": "Community name is taken. Try again.",
    "titleTellUs": "Tell us more about your community",
    "paragrapheTellUs": "Your community site will automatically appear in the gcxchange Catalogue for quick and easy searching. Giving us a short description will help others should they want to reach out to you.",
    "validationTxtTellUs": "Each one must be a minimum of 5 characters and a maximum of 500 characters long.",
    "businessReason": "Business reason",
    "phLetus": "Let people know what your community is all about",
    "phBusinessReason": "Explain the purpose of this community",
    "titleOwners": "Invite owners",
    "paragrapheOwners": "As a gcxchange Owner you can modify your SharePoint storefront and invite other users to your community so they can collaborate with you in Microsoft Teams. We will provide you with detailed information on adding users when your space is created.",
    "validationTxtOwners": "For now, we need one or two additional Owners before your site can be created:",
    "owners": "Owners",
    "titleReview": "Review and submit!",
    "templateTitle": "Template title",
    "spaceName": "Community name",
    "spaceDescEn":"Community description (EN)",
    "spaceDescFr": "Community description (FR)",
    "teamPurpose": "Community Purpose and content",
    "btnSubmit": "Let's do this!",
    "btnChecksite": "Check availability",
    "congrats": "Congratulations!",
    "congratPara1": "Thank you for your submission.",
    "congratPara2": "You will receive an email when your community has been created with everything you need to get started! (within 24 to 48 hours Monday to Friday)",
    "congratHome": "Home",
    "congratPara3": "If you do not receive the email or you have any questions please submit a service request using the",
    "congratLink": "gcxchange Support portal",
    "altTemplate": "Image of template ",
    "templateButtonLabel": "Select template ",
    "iconLoading": "loading icon",
    "textLoading": "Your infomation is sending, thanks for your patience",
    "altWelcome": "SharePoint and Microsoft Teams sharing information",
    "altCongrat": "",
    "ownerInfo1": "Can’t find a person when you search for their name?  ",
    "ownerInfo2": "It’s likely they haven't registered yet for gcxchange. ",
    "ownerInfo3": "Please ask them to register first by … ",
    "ownerInfo4": "Then come on back to request your community. ",
    "tooltipWelImg": "SharePoint and Microsoft Teams sharing information",
    "tooltipWelBtn": "Let's go!",
    "tooltipspaceNameEn": "Type the English community name",
    "tooltipspaceNameFr": "Type the French community name",
    "tooltipchecksite": "Check the availability of the community name",
    "tooltipdescEn": "Type the English description",
    "tooltipdescFr": "Type the French description",
    "tooltipBusReason": "Type the business reason for your community",
    "tooltipOwners": "Add owners",
    "tooltipBtnBack": "Go back one screen",
    "tooltipBtnNext": "Next screen",
    "tooltipBtnEnd": "Let's do this",
    "tooltipBtnCancel": "Cancel",
    "NextBtn": "Next",
    "BackBtn": "Previous",
    "CancelBtn": "Cancel",
    "ErrMustLetter": "Must contain letters and numbers only",
  }
});