define([], function() {
  return {
    "userLang": "FR",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "ListTemplateFieldLabel": "Nom de la liste",
    "TitleCreate": "Title create",
    "createSpace": "Créez une collectivité",
    "paragrapheHome": "Collaborez avec vos collègues de tous les ministères en utilisant Microsoft Teams et SharePoint, où les idées et les documents circulent facilement de l’un à l’autre. ",
    "startButton": "C'est parti!",
    "powered": "Alimenté par",
    "gcx": "GCÉchange",
    "menuFinal": "Allons de l’avant",
    "menuOwners": "Convoquez les propriétaires",
    "menuTell": "Dites-nous en davantage",
    "menuSpace": "Nommez votre collectivité",
    "menuTemplate": "Choisissez un gabarit",
    "titleTemplate": "Choisissez votre gabarit SharePoint",
    "paragrapheTemplate": "SharePoint sert de vitrine à votre collectivité et fait la promotion de votre collectivité auprès des visiteurs de GCÉchange. Choisissez un modèle qui correspond le mieux à l’objectif de votre collectivité. Vous serez en mesure de le modifier lorsque vous l’aurez créé.",
    "titleSpace": "Donnez un nom bilingue à votre collectivité",
    "paragrapheSpace": "Pourquoi un nom bilingue? Un nom bilingue est conforme à la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre espace SharePoint dans le catalogue GCÉchange.",
    "validationTxtSpace": "Chaque nom doit contenir uniquement des lettres et des chiffres. Chaque nom doit comporter pas moins de 5 caractères et pas plus de 125 caractères.",
    "english": "Nom de votre de collectivité en anglaise",
    "french": "Nom de votre de collectivité en français",
    "validationSpaceInput": "Doit contenir uniquement des lettres et des chiffres",
    "greatChoice": "Excellent choix!",
    "siteTaken": "Le nom de la collectivité est déjà utilisé. Essayez de nouveau.",
    "titleTellUs": "Parlez-nous davantage de votre collectivité",
    "paragrapheTellUs": "Le site de votre collectivité apparaîtra automatiquement dans le catalogue GCÉchange afin de favoriser une recherche rapide et facile. En nous donnant une brève description, vous faciliterez la tâche aux autres personnes qui désireraient communiquer avec vous.",
    "validationTxtTellUs": "Chaque nom doit comporter pas moins de 5 caractères et pas plus de 500 caractères.",
    "businessReason": "Raison d’affaires",
    "phLetusEn": "Faites savoir au monde en quoi consiste le but de cette collectivité en anglais.",
    "phLetusFr": "Faites savoir au monde en quoi consiste le but de cette collectivité en français.",
    "phBusinessReason": "Expliquer le but de cette collectivité",
    "titleOwners": "Convoquez les propriétaires",
    "paragrapheOwners": "En tant que propriétaire de GCéchange, vous pouvez modifier votre site Sharepoint et inviter d'autres utilisauteurs dans votre collectivité afin qu'ils pussent collaborer avec vous dans Microsoft Teams.",
    "validationTxtOwners": "Pour l’instant, nous avons besoin d’un ou deux propriétaires supplémentaires avant de pouvoir créer votre site :",
    "owners": "Propriétaires",
    "titleReview": "Passez en revue et soumettez!",
    "templateTitle": "Titre du gabarit",
    "spaceName": "Nom de la collectivité",
    "spaceDescEn":"Description de la collectivité en anglais",
    "spaceDescFr": "Description de la collectivité en français",
    "teamPurpose": "Objectif et contenu de la collectivité",
    "btnSubmit": "Allons de l'avant!",
    "btnChecksite": "Vérifier la disponibilité",
    "congrats": "Félicitations!",
    "congratPara1": "Nous vous remercions de votre demande.",
    "congratPara2": "Vous recevrez un courriel lorsque votre collectivité aura été créé avec tout ce dont vous avez besoin pour commencer! (dans les 24 à 48 heures du lundi au vendredi)",
    "congratHome": "Accueil",
    "congratPara3": "Si vous ne recevez pas de courriel ou si vous avez des questions, veuillez soumettre une demande de service à l’aide du",
    "congratLink": "portail de soutien GCÉchange",
    "altTemplate": "Image du gabarit ",
    "templateButtonLabel": "Selectionnez gabarit ",
    "iconLoading": "Icône de chargement",
    "textLoading": "Vos données sont entrain d'être envoyé, merci de votre patience ",
    "altWelcome": "SharePoint et Microsoft Teams échangent de l’information",
    "altCongrat": "",
    "ownerInfo1": "Si vous ne trouvez pas le nom de la personne que vous cherchez,",
    "ownerInfo2": " elle n'est probablement pas encore enregistrée à GCÉchange.",
    "ownerInfo3": "Demandez-leur de s'enregister …  ",
    "ownerInfo4": "Puis recommencez le processus d'inscription de collectivité. ",
    "tooltipWelImg": "SharePoint et Microsoft Teams échangent de l’information",
    "tooltipWelBtn": "C'est parti!",
    "tooltipspaceNameEn": "Saisissez le nom de la collectivité en anglais",
    "tooltipspaceNameFr": "Saisissez le nom de la collectivité en français",
    "tooltipchecksite": "Vérifier la disponibilité du nom de la collectivité",
    "tooltipdescEn": "Saisissez la description en anglais",
    "tooltipdescFr": "Saisissez la description en français",
    "tooltipBusReason": "Expliquer la raison d'affaire de votre collectivité",
    "tooltipOwners": "Ajoutez des propriétaires",
    "tooltipBtnBack": "Revenez à l'écran précédent.",
    "tooltipBtnNext": "Écran suivant",
    "tooltipBtnEnd": "Allons de l'avant",
    "tooltipBtnCancel": "Annulez",
    "NextBtn": "Suivant",
    "BackBtn": "Revenez en arrière",
    "CancelBtn": "Annulez",
    "ErrMustLetter": "Doit contenir uniquement des lettres, des chiffres et certains caractères spéciaux (()&,/#). Chaque nom doit comporter pas moins de 5 caractères et pas plus de 125 caractères",
    "DescriptionHelperText": "Chaque nom doit comporter pas moins de 5 caractères et pas plus de 500 caractères",
    "lastStepMakeChanges": "Si vous devez apporter des modifications, cliquez sur le bouton précédent ci-dessous pour modifier les pages précédentes de votre soumission."
  }
});
