define([], function() {
  return {
    "userLang": "FR",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "ListTemplateFieldLabel": "Nom de la liste",
    "TitleCreate": "Title create",
    "createSpace": "Créez une communauté",
    "paragrapheHome": "Collaborez avec vos collègues de tous les ministères en utilisant Microsoft Teams et SharePoint, où les idées et les documents circulent facilement de l’un à l’autre. ",
    "startButton": "C'est parti!",
    "powered": "Alimenté par",
    "gcx": "gcéchange",
    "menuFinal": "Allons de l’avant",
    "menuOwners": "Convoquez les propriétaires",
    "menuTell": "Dites-nous en davantage",
    "menuSpace": "Nommez votre communauté",
    "menuTemplate": "Choisissez un gabarit",
    "titleTemplate": "Choisissez votre modèle SharePoint",
    "paragrapheTemplate": "SharePoint sert de vitrine à votre communauté et fait la promotion de votre communauté auprès des visiteurs de gcéchange. Choisissez un modèle qui correspond le mieux à l’objectif de votre communauté. Vous serez en mesure de le modifier lorsque vous l’aurez créé.",
    "titleSpace": "Donnez un nom bilingue à votre communauté",
    "paragrapheSpace": "Pourquoi un nom bilingue? Un nom bilingue est conforme à la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre espace SharePoint dans le catalogue gcéchange.",
    "validationTxtSpace": "Chaque nom doit contenir uniquement des lettres et des chiffres. Chaque nom doit comporter pas moins de 5 caractères et pas plus de 125 caractères.",
    "english": "Anglais",
    "french": "Français",
    "validationSpaceInput": "Doit contenir uniquement des lettres et des chiffres",
    "greatChoice": "Excellent choix!",
    "siteTaken": "Le nom de la communauté est déjà utilisé. Essayez de nouveau.",
    "titleTellUs": "Parlez-nous davantage de votre communauté ",
    "paragrapheTellUs": "Le site de votre communauté apparaîtra automatiquement dans le catalogue gcéchange afin de favoriser une recherche rapide et facile. En nous donnant une brève description, vous faciliterez la tâche aux autres personnes qui désireraient communiquer avec vous.",
    "validationTxtTellUs": "Chaque nom doit comporter pas moins de 5 caractères et pas plus de 500 caractères.",
    "businessReason": "Raison d’affaires",
    "phLetus": "Faites savoir au monde en quoi consiste le but de cette communauté en anglais",
    "phBusinessReason": "Expliquer le but de cette communauté",
    "titleOwners": "Convoquez les propriétaires",
    "paragrapheOwners": "En tant que propriétaire de gcéchange, vous pouvez modifier votre vitrine SharePoint et inviter d’autres personnes dans votre communauté afin qu’elles puissent collaborer avec vous dans votre atelier (Microsoft Teams). Nous vous donnerons des renseignements détaillés sur l’ajout d’utilisateurs lorsque votre communauté sera créé.",
    "validationTxtOwners": "Pour l’instant, nous avons besoin d’un ou deux propriétaires supplémentaires avant de pouvoir créer votre site :",
    "owners": "Propriétaires",
    "titleReview": "Passez en revue et soumettez!",
    "templateTitle": "Titre du modèle",
    "spaceName": "Nom de la communauté",
    "spaceDescEn":"Description de la communauté en anglais",
    "spaceDescFr": "Description de la communauté en français",
    "teamPurpose": "Objectif et contenu de la communauté",
    "btnSubmit": "Allons de l'avant!",
    "btnChecksite": "Vérifier la disponibilité",
    "congrats": "Félicitations!",
    "congratPara1": "Nous vous remercions de votre demande.",
    "congratPara2": "Vous recevrez un courriel lorsque votre communauté aura été créé avec tout ce dont vous avez besoin pour commencer! (dans les 24 à 48 heures du lundi au vendredi)",
    "congratHome": "Accueil",
    "congratPara3": "Si vous ne recevez pas de courriel ou si vous avez des questions, veuillez soumettre une demande de service à l’aide du",
    "congratLink": "portail de soutien gcéchange",
    "altTemplate": "Image du gabarit ",
    "templateButtonLabel": "Selectionnez gabarit ",
    "iconLoading": "Icône de chargement",
    "textLoading": "Vos données sont entrain d'être envoyé, merci de votre patience ",
    "altWelcome": "SharePoint et Microsoft Teams échangent de l’information",
    "altCongrat": "",
    "ownerInfo1": "Vous ne trouvez pas le nom que vous cherchez?",
    "ownerInfo2": "Il semblerait qu'ils ne se sont pas encore enregistrés pour gcéchange",
    "ownerInfo3": "Svp, demander-leurs de s'enregistrer en premier …  ",
    "ownerInfo4": "Puis revenez demander votre communauté ",
    "tooltipWelImg": "SharePoint et Microsoft Teams échangent de l’information",
    "tooltipWelBtn": "C'est parti!",
    "tooltipspaceNameEn": "Saisissez le nom de la communauté en anglais",
    "tooltipspaceNameFr": "Saisissez le nom de la communauté en français",
    "tooltipchecksite": "Vérifier la disponibilité du nom de la communauté",
    "tooltipdescEn": "Saisissez la description en anglais",
    "tooltipdescFr": "Saisissez la description en français",
    "tooltipBusReason": "Expliquer la raison d'affaire de votre communauté",
    "tooltipOwners": "Ajoutez des propriétaires",
    "tooltipBtnBack": "Revenez à l'écran précédent.",
    "tooltipBtnNext": "Écran suivant",
    "tooltipBtnEnd": "Allons de l'avant",
    "tooltipBtnCancel": "Annulez",
    "NextBtn": "Suivant",
    "BackBtn": "Revenez en arrière",
    "CancelBtn": "Annulez",
    "ErrMustLetter": "Doit contenir uniquement des lettres, des chiffres et certains caractères spéciaux (()&,/#). Chaque nom doit comporter pas moins de 5 caractères et pas plus de 125 caractères",
    "DescriptionHelperText": "Chaque nom doit comporter pas moins de 5 caractères et pas plus de 500 caractères",
  }
});